# These properties are for your JMeter controller. remote_host tells JMeter where your remote
# servers are (can do multiple comma separated). The ssl property is just for making the demo 
# easier to set up
remote_hosts=remote.ip.address
server.rmi.ssl.disable=true